"""Added Session

Revision ID: 14cfe3d87cae
Revises: d626a2747030
Create Date: 2024-09-18 11:08:43.930532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14cfe3d87cae'
down_revision = 'd626a2747030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=80), nullable=False),
    sa.Column('notification_token', sa.String(length=80), nullable=True),
    sa.Column('date_of_creation', sa.DateTime(), nullable=False),
    sa.Column('date_of_expiration', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    op.drop_table('sessions')
    # ### end Alembic commands ###
