"""changes

Revision ID: 34730f34b9d9
Revises: aa977e63d914
Create Date: 2024-09-22 19:07:15.228425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34730f34b9d9'
down_revision = 'aa977e63d914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=44),
               type_=sa.String(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('position',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=44),
               existing_nullable=True)

    # ### end Alembic commands ###
