"""test

Revision ID: 58015a6f1e0b
Revises: 93699b4f50bc
Create Date: 2024-09-30 15:11:31.918493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58015a6f1e0b'
down_revision = '93699b4f50bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can', sa.Boolean(), nullable=True))

    op.execute('UPDATE permissions SET can = false')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.alter_column('can', existing_type=sa.Boolean(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_column('can')

    # ### end Alembic commands ###
