"""position for person in project

Revision ID: 7250e698f6d0
Revises: b500262b187f
Create Date: 2024-09-29 10:09:17.102492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7250e698f6d0'
down_revision = 'b500262b187f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_in_project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_in_project', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_in_project', schema=None) as batch_op:
        batch_op.drop_column('position_in_project')

    # ### end Alembic commands ###
