"""add sort_order to person_in_project

Revision ID: 882aa70ee689
Revises: eb00ad9c7ab6
Create Date: 2024-09-20 15:19:20.373242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882aa70ee689'
down_revision = 'eb00ad9c7ab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_in_project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_in_project', schema=None) as batch_op:
        batch_op.drop_column('sort_order')

    # ### end Alembic commands ###
