"""new permission option

Revision ID: 91627831e145
Revises: ed18738d6933
Create Date: 2024-09-21 21:53:13.612035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91627831e145'
down_revision = 'ed18738d6933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_edit_settings_project', sa.Boolean()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_column('can_edit_settings_project')

    # ### end Alembic commands ###
