"""position for creator in project

Revision ID: 93699b4f50bc
Revises: 7250e698f6d0
Create Date: 2024-09-29 10:42:28.127982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93699b4f50bc'
down_revision = '7250e698f6d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_creator_in_project', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('position_creator_in_project')

    # ### end Alembic commands ###
