"""nullable=False for permission

Revision ID: aa977e63d914
Revises: 91627831e145
Create Date: 2024-09-21 21:57:18.382275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa977e63d914'
down_revision = '91627831e145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.alter_column('can_edit_settings_project',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.alter_column('can_edit_settings_project',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
