"""added date of creation and join

Revision ID: b500262b187f
Revises: f821a198654e
Create Date: 2024-09-28 22:48:16.210192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b500262b187f'
down_revision = 'f821a198654e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_in_project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_join', sa.DateTime(), nullable=True))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_creation', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_creation', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('date_of_creation')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('date_of_creation')

    with op.batch_alter_table('person_in_project', schema=None) as batch_op:
        batch_op.drop_column('date_of_join')

    # ### end Alembic commands ###
